<?php
/**
 * Миграция m140418_045834_upadte_localities
 *
 * @property string $prefix
 */
 
class m140418_045834_upadte_localities extends CDbMigration
{
    public function up(){
        $this->truncateTable('{{land_localities}}');
        $this->insertMultiple('{{land_localities}}', array(
            array('name' => 'Тюмень'),
            array('name' => 'Андреевский'),
            array('name' => 'Богандинка'),
            array('name' => 'Борки'),
            array('name' => 'Щербак'),
            array('name' => 'Боровский'),
            array('name' => 'Винзили'),
            array('name' => 'Горьковка'),
            array('name' => 'Утешевский'),
            array('name' => 'Ембаево'),
            array('name' => 'Тураева'),
            array('name' => 'Яр'),
            array('name' => 'Каменка'),
            array('name' => 'Коняшина'),
            array('name' => 'Кулига'),
            array('name' => 'Насекина'),
            array('name' => 'Речкина'),
            array('name' => 'Каскара'),
            array('name' => 'Вилижаны'),
            array('name' => 'Новотуринский'),
            array('name' => 'Янтык'),
            array('name' => 'Княжево'),
            array('name' => 'Кыштырла'),
            array('name' => 'Песьянка'),
            array('name' => 'Кулаково'),
            array('name' => 'Луговое'),
            array('name' => 'Мальково'),
            array('name' => 'Ошкукова'),
            array('name' => 'Паренкина'),
            array('name' => 'Субботина'),
            array('name' => 'Московский'),
            array('name' => 'Гусево'),
            array('name' => 'Дударева'),
            array('name' => 'Падерина'),
            array('name' => 'Посохова'),
            array('name' => 'Муллаши'),
            array('name' => 'Нариманова'),
            array('name' => 'Новотарманский '),
            array('name' => 'Молчанова '),
            array('name' => 'Решетникова '),
            array('name' => 'Туринский '),
            array('name' => 'Онохино'),
            array('name' => 'Головина'),
            array('name' => 'Перевалово'),
            array('name' => 'Елань '),
            array('name' => 'Зубарева '),
            array('name' => 'Подъем '),
            array('name' => 'Ушакова '),
            array('name' => 'Салаирка'),
            array('name' => 'Созоново'),
            array('name' => 'Успенка '),
            array('name' => 'Гужевое '),
            array('name' => 'Зырянка '),
            array('name' => 'Малиновка '),
            array('name' => 'Чаплык '),
            array('name' => 'Червишево'),
            array('name' => 'Большие Акияры'),
            array('name' => 'Друганова '),
            array('name' => 'Костылева '),
            array('name' => 'Леваши '),
            array('name' => 'Малые Акияры '),
            array('name' => 'Мичурино '),
            array('name' => 'Черная Речка '),
            array('name' => 'Чикча'),
            array('name' => 'Большие Акияры '),
            array('name' => 'Друганова '),
            array('name' => 'Костылева'),
            array('name' => 'Леваши '),
            array('name' => 'Малые Акияры '),
            array('name' => 'Мичурино '),
            array('name' => 'Черная Речка '),
            array('name' => 'Антипино  '),
            array('name' => 'Березняковский '),
            array('name' => 'Быкова '),
            array('name' => 'Верхний Бор  '),
            array('name' => 'Воронина  '),
            array('name' => 'Гилева  '),
            array('name' => 'Дорожный  '),
            array('name' => 'Зайкова  '),
            array('name' => 'Источни  '),
            array('name' => 'Казарово  '),
            array('name' => 'Княжева  '),
            array('name' => 'Комарово  '),
            array('name' => 'Копытова  '),
            array('name' => 'Матмасы  '),
            array('name' => 'Метелева  '),
            array('name' => 'Плеханова  '),
            array('name' => 'Рощино  '),
            array('name' => 'Тараскуль  '),
            array('name' => 'Тарманы  '),
            array('name' => 'Утешева  '),
            array('name' => 'Патрушева'),
            array('name' => 'Ожогина'),
            array('name' => 'Московский дворик'),
            array('name' => 'Березники '),
            array('name' => 'Мияссы '),
            array('name' => 'Морозовка '),
            array('name' => 'Нижнепристанской '),
            array('name' => 'Первомайский'),
            array('name' => 'Богандинское '),
            array('name' => 'Аманадское '),
            array('name' => 'Железный Перебор '),
            array('name' => 'Марай '),
            array('name' => 'Пышминка '),
            array('name' => 'Красный Яр'),
            array('name' => 'Андрюшино'),
            array('name' => 'Антропово'),
            array('name' => 'Девятково   '),
            array('name' => 'Антипино'),
            array('name' => 'Вершина '),
            array('name' => 'Елань '),
            array('name' => 'Камышинка '),
            array('name' => 'Кускургуль '),
            array('name' => 'Троицкое '),
            array('name' => 'Турнаева '),
            array('name' => 'Березовка '),
            array('name' => 'Калиновка '),
            array('name' => 'Соколовка '),
            array('name' => 'Бухтал '),
            array('name' => 'Ахманы '),
            array('name' => 'Казанка '),
            array('name' => 'Новоказанка '),
            array('name' => 'Новопокровка '),
            array('name' => 'Новоуфимка '),
            array('name' => 'Велижаны '),
            array('name' => 'Аракчина '),
            array('name' => 'Малые Велижаны '),
            array('name' => 'Московка '),
            array('name' => 'Иска '),
            array('name' => 'Большой Хутор '),
            array('name' => 'Красный Яр '),
            array('name' => 'Малый Хутор '),
            array('name' => 'Тандашково '),
            array('name' => 'Канаш '),
            array('name' => 'Белая Дуброва '),
            array('name' => 'Понизовка '),
            array('name' => 'Ключи '),
            array('name' => 'Гузенеевский '),
            array('name' => 'Ипкуль '),
            array('name' => 'Кунчур '),
            array('name' => 'Мияги '),
            array('name' => 'Тангачи '),
            array('name' => 'Торгили '),
            array('name' => 'Шапкуль '),
            array('name' => 'Миясское    '),
            array('name' => 'Нижняя Тавда '),
            array('name' => 'Черноярка '),
            array('name' => 'Новоникольское '),
            array('name' => 'Ахманский '),
            array('name' => 'Веселая Грива '),
            array('name' => 'Герасимовка '),
            array('name' => 'Новотроицкое '),
            array('name' => 'Иска-Чебакова '),
            array('name' => 'Картымский '),
            array('name' => 'Новоникольская '),
            array('name' => 'Тукман '),
            array('name' => 'Тюнево '),
            array('name' => 'Карагандинский '),
            array('name' => 'Лесозаводский '),
            array('name' => 'Носырево '),
            array('name' => 'Штакульская '),
            array('name' => 'Черепаново '),
            array('name' => 'Бугры '),
            array('name' => 'Еремино '),
            array('name' => 'Крысова '),
            array('name' => 'Сосновка '),
            array('name' => 'Чугунаево'),
            array('name' => 'Покровское '),
            array('name' => 'Дулепина '),
            array('name' => 'Никитина '),
            array('name' => 'Ярково '),
            array('name' => 'Мостовой '),
            array('name' => 'Светлоозерский '),
            array('name' => 'Южаково '),
        ));
    }

    public function down(){
        $this->truncateTable('{{land_localities}}');
        $this->insertMultiple('{{land_localities}}', array(
            array('name' => 'Аманадское', 'city_id' => 11),
            array('name' => 'Андреевский', 'city_id' => 11),
            array('name' => 'Богандинский', 'city_id' => 11),
            array('name' => 'Богандинское', 'city_id' => 11),
            array('name' => 'Большие Акияры', 'city_id' => 11),
            array('name' => 'Борки', 'city_id' => 11),
            array('name' => 'Боровский', 'city_id' => 11),
            array('name' => 'Вилижаны', 'city_id' => 11),
            array('name' => 'Винзили', 'city_id' => 11),
            array('name' => 'Головина', 'city_id' => 11),
            array('name' => 'Горьковка', 'city_id' => 11),
            array('name' => 'Гужевое', 'city_id' => 11),
            array('name' => 'Гусево', 'city_id' => 11),
            array('name' => 'Дербыши', 'city_id' => 11),
            array('name' => 'Друганова', 'city_id' => 11),
            array('name' => 'Дударева', 'city_id' => 11),
            array('name' => 'Елань', 'city_id' => 11),
            array('name' => 'Ембаево', 'city_id' => 11),
            array('name' => 'Есаулова', 'city_id' => 11),
            array('name' => 'Железный Перебор', 'city_id' => 11),
            array('name' => 'Зубарева', 'city_id' => 11),
            array('name' => 'Зырянка', 'city_id' => 11),
            array('name' => 'Каменка', 'city_id' => 11),
            array('name' => 'Каскара', 'city_id' => 11),
            array('name' => 'Княжево', 'city_id' => 11),
            array('name' => 'Коняшина', 'city_id' => 11),
            array('name' => 'Костылева', 'city_id' => 11),
            array('name' => 'Криводанова', 'city_id' => 11),
            array('name' => 'Кулаково', 'city_id' => 11),
            array('name' => 'Кулига', 'city_id' => 11),
            array('name' => 'Кыштырла', 'city_id' => 11),
            array('name' => 'Леваши', 'city_id' => 11),
            array('name' => 'Луговое', 'city_id' => 11),
            array('name' => 'Малиновка', 'city_id' => 11),
            array('name' => 'Малые Акияры', 'city_id' => 11),
            array('name' => 'Мальково', 'city_id' => 11),
            array('name' => 'Марай', 'city_id' => 11),
            array('name' => 'Мичурино', 'city_id' => 11),
            array('name' => 'Молчанова', 'city_id' => 11),
            array('name' => 'Московский', 'city_id' => 11),
            array('name' => 'Муллаши', 'city_id' => 11),
            array('name' => 'Нариманова', 'city_id' => 11),
            array('name' => 'Насекина', 'city_id' => 11),
            array('name' => 'Новотарманский', 'city_id' => 11),
            array('name' => 'Новотуринский', 'city_id' => 11),
            array('name' => 'Ожогина', 'city_id' => 11),
            array('name' => 'Онохино', 'city_id' => 11),
            array('name' => 'Ошкукова', 'city_id' => 11),
            array('name' => 'Падерина', 'city_id' => 11),
            array('name' => 'Паренкина', 'city_id' => 11),
            array('name' => 'Патрушева', 'city_id' => 11),
            array('name' => 'Перевалово', 'city_id' => 11),
            array('name' => 'Песьянка', 'city_id' => 11),
            array('name' => 'Подъем', 'city_id' => 11),
            array('name' => 'Посохова', 'city_id' => 11),
            array('name' => 'Пышма', 'city_id' => 11),
            array('name' => 'Пышминка', 'city_id' => 11),
            array('name' => 'Речкина', 'city_id' => 11),
            array('name' => 'Решетникова', 'city_id' => 11),
            array('name' => 'Салаирка', 'city_id' => 11),
            array('name' => 'Созоново', 'city_id' => 11),
            array('name' => 'Субботина', 'city_id' => 11),
            array('name' => 'Тураева', 'city_id' => 11),
            array('name' => 'Туринский', 'city_id' => 11),
            array('name' => 'Успенка', 'city_id' => 11),
            array('name' => 'Утешевский', 'city_id' => 11),
            array('name' => 'Ушакова', 'city_id' => 11),
            array('name' => 'Чаплык', 'city_id' => 11),
            array('name' => 'Червишево', 'city_id' => 11),
            array('name' => 'Черная Речка', 'city_id' => 11),
            array('name' => 'Чикча', 'city_id' => 11),
            array('name' => 'Щербак', 'city_id' => 11),
            array('name' => 'Якуши', 'city_id' => 11),
            array('name' => 'Янтык', 'city_id' => 11),
            array('name' => 'Яр', 'city_id' => 11),
            array('name' => 'Андрюшинское', 'city_id' => 12),
            array('name' => 'Антипинское', 'city_id' => 12),
            array('name' => 'Березовское', 'city_id' => 12),
            array('name' => 'Бухтальское', 'city_id' => 12),
            array('name' => 'Велижанское', 'city_id' => 12),
            array('name' => 'Искинское', 'city_id' => 12),
            array('name' => 'Канашское', 'city_id' => 12),
            array('name' => 'Ключевское', 'city_id' => 12),
            array('name' => 'Миясское', 'city_id' => 12),
            array('name' => 'Нижнетавдинское', 'city_id' => 12),
            array('name' => 'Новоникольское', 'city_id' => 12),
            array('name' => 'Новотроицкое', 'city_id' => 12),
            array('name' => 'Тавдинское', 'city_id' => 12),
            array('name' => 'Тарманское', 'city_id' => 12),
            array('name' => 'Тюневское', 'city_id' => 12),
            array('name' => 'Чугунаевское', 'city_id' => 12),
            array('name' => 'Архангельское', 'city_id' => 13),
            array('name' => 'Бархатовское', 'city_id' => 13),
            array('name' => 'Бобылевское', 'city_id' => 13),
            array('name' => 'Верхнебешкильское', 'city_id' => 13),
            array('name' => 'Верхнеингальское', 'city_id' => 13),
            array('name' => 'Денисовское', 'city_id' => 13),
            array('name' => 'Исетское', 'city_id' => 13),
            array('name' => 'Кировское', 'city_id' => 13),
            array('name' => 'Коммунаровское', 'city_id' => 13),
            array('name' => 'Красновское', 'city_id' => 13),
            array('name' => 'Мининское', 'city_id' => 13),
            array('name' => 'Рассветовское', 'city_id' => 13),
            array('name' => 'Рафайловское', 'city_id' => 13),
            array('name' => 'Слободобешкильское', 'city_id' => 13),
            array('name' => 'Солобоевское', 'city_id' => 13),
            array('name' => 'Шороховское', 'city_id' => 13)
        ));
    }
}